### ISSUE TITLE
Add support to aggregate multiple queries into a single response

### ISSUE THREAD

**Issue by php-coder** [php-coder/query2app#17]
It should be possible to return a multiple members where each of them are came from different queries.

**Comment by php-coder** [comment]
Example of a response:
```json
{
  "num_of_categories": 5,
  "num_of_ countries": 10
  "num_of_ series": 100
}
```
And possible syntax:
```yaml
- path: /v1/stat
  get:
    queries:
      num_of_categories: SELECT COUNT(*) FROM categories
      num_of_ countries: SELECT COUNT(*) FROM countries
      num_of_ series: SELECT COUNT(*) FROM series
```
OR
```yaml
- path: /v1/stat
  get:
    aggregated_query:
      num_of_categories: SELECT COUNT(*) FROM categories
      num_of_ countries: SELECT COUNT(*) FROM countries
      num_of_ series: SELECT COUNT(*) FROM series
```
OR
```yaml
- path: /v1/stat
  get:
    query:
      aggregate:
        num_of_categories: SELECT COUNT(*) FROM categories
        num_of_ countries: SELECT COUNT(*) FROM countries
        num_of_ series: SELECT COUNT(*) FROM series
```
