### ISSUE TITLE
How to distinguish controllers that return a single object or a list?

### ISSUE THREAD

**Issue by php-coder** [php-coder/query2app#7]

**Comment by php-coder** [comment]
Option 1: use rules for guessing what is expected to be returned.

For example, `SELECT COUNT(*) FROM ...` will always return a single object (as well as usage of other aggregated functions. If a query has `LIMIT 1` or `WHERE id = :id` it also returns a single row.

Pros:
- user doesn't need to think as everything works out-of-the-box

Cons:
- user should know (or learn) our conventions
- we'll have to maintain a lot of rules
- there always will be a case when we missed user's expectations anyway (what if `id` field isn't unique or what if my query has `WHERE slug = ?` and `slug` field is unique but we don't take it into account)

**Comment by php-coder** [comment]
**Option 2: let user to specify what is expected in the result**

* 2.1: introduce a separate field for that
* 2.2: introduce a separate field with a list of hints (that could be useful in future for other cases)
* 2.3: modify/enhance a method field
```yaml
- path: /categories/:id
  get_one:  SELECT id,name FROM categories WHERE id = :id
- path: /categories
  get_many:  SELECT id,name FROM categories
```

**Comment by theshamuel** [comment]
Hey @php-coder, I suppose, that option 2.1 is more suitable for fixing your issue. Because but no matter as you wish you cannot avoid adding new field, so it had better been more clear for understanding for user. That is why modify `get_` and creating one common` hints` looks a little bit weird for me. If you use field `return: list/object` I think it is really obvious what for it.

**Comment by php-coder** [comment]
After discussions I started to think about introducing a single field. I had something like this in mind:
```yaml
input:
  ...
output:
  multiple: true      <-- look here
  type: PersonDto
  fields:
    id: int
    name: string
```
Because I can't predict future and I can't suggest an option that I would be happy with, I've decided to go with the simplest and fastest approach right now. I will change API when I have more use-cases. In 44c061d85a69a964496cfffebfe21a008fc4c75d I introduced `get_list` verb.

I leave the issue open because I anticipate that the current solution will be revised in future.
